### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by Raissa-Cardoso**
I created a button to switch between light and dark modes. And add moon light image

### CODE REVIEW

**Comment by PankajSingh2003** [comment]
Well thanks for the effort that you made.
Really appreciate it . !!!! 
: )

**Comment by PankajSingh2003** [comment]
There you go added the badges as well.
Hope you have a wonderful day ahead. 
keep going.

**Comment by Raissa-Cardoso** [comment]
Can you, please, add add the hacktoberfest-accepted label?

**Comment by PankajSingh2003** [comment]
There you go the hactoberfest one should do the trick .
But since you insist so added this one as well.

Peace !!!!

**Pull request merged**
