### PR TITLE
removed text overlapping

### PR DESCRIPTION
**Pull request by Tatwansh**
Here I have made changes in index.html as well as style.css .

### CODE REVIEW

**Comment by PankajSingh2003** [comment]
Brother this pr request is showing conflict.or i would have accepted it a long time ago.

You can see for yourself

**Comment by PankajSingh2003** [comment]
Well if you want just make a small change pr request sync your repo.
I will accept it. It probably showing that because someone has already fixed it .
Or the time you made change the repo already had some changes.

Sorry for the inconvenience mate !!!

**Comment by PankajSingh2003** [comment]
Borther i had fixed the conflict myself. It took some time .
That's the reason it took so long to accept your request. By the thanks for your effort man .
Just in case you will be trying more contributions try to sync the repo your doing. it will really be beneficial.
:)

**Comment by Tatwansh** [comment]
Sure brother. Will keep that in mind.

**Pull request merged**
